customCommands:
  - key: 'J'
    command: "get-tickets"
    context: 'files'
    description: 'Show my tickets'
    subprocess: true
  - key: 'j'
    command: "get-tickets {{ `{{.SelectedFile.Name}}` }}"
    context: 'files'
    description: 'Show file tickets'
    subprocess: true
  - key: 'f'
    command: "git difftool -y {{ `{{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}}` }}"
    context: 'commitFiles'
    description: 'Compare (difftool) with local copy'
  - key: "<c-p>"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"
  - key: "v" # couldn't think of a better keybinding
    prompts:
      - type: 'input'
        title: 'PR id:'
    command: "hub pr checkout {{ `{{index .PromptResponses 0}}` }}"
    context: "localBranches"
    loadingText: "checking out PR"
  - key: b
    command: tig blame -- {{ `{{.SelectedFile.Name}}` }}
    context: files
    description: blame file at tree
    subprocess: true
  - key: b
    command: tig blame {{ `{{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}` }}
    context: commitFiles
    description: blame file at revision
    subprocess: true
  - key: B
    command: tig blame -- {{ `{{.SelectedCommitFile.Name}}` }}
    context: commitFiles
    description: blame file at tree
    subprocess: true
  - key: t
    command: tig show {{ `{{.SelectedSubCommit.Sha}}` }}
    context: subCommits
    description: tig commit (`t` again to browse files at revision)
    subprocess: true
  - key: t
    command: tig show {{ `{{.SelectedLocalBranch.Name}}` }}
    context: localBranches
    description: tig branch (`t` again to browse files at revision)
    subprocess: true
  - key: t
    command: tig show {{ `{{.SelectedRemoteBranch.RemoteName}}/{{.SelectedRemoteBranch.Name}}` }}
    context: remoteBranches
    description: tig branch (`t` again to browse files at revision)
  - key: t
    command: tig {{ `{{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}` }}
    context: commitFiles
    description: tig file (history of commits affecting file)
    subprocess: true
  - key: t
    command: tig -- {{ `{{.SelectedFile.Name}}` }}
    context: files
    description: tig file (history of commits affecting file)
    subprocess: true
